FROM node:12

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install
# RUN npm i -g ts-node

COPY ./build/ .
CMD ["node", "--require=source-map-support/register", "src/server.api.js"]
